# Generated by Django 6.1 on 2026-08-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(help_text='Number of servings')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calories_kcal', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('saturated_fat_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('cholesterol_mg', models.FloatField(default=0)),
                ('potassium_mg', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (1-3 days/week)'), ('moderate', 'Moderately active (3-5 days/week)'), ('active', 'Very active (6-7 days/week)'), ('extra', 'Extra active (physical job/training)')], default='sedentary', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
