# Generated by Django 6.1 on 2026-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL returned by the food API', null=True),
        ),
    ]
